# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='homepage_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='language',
            name='homepage_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='languages.Language'),
        ),
    ]
