# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20151222_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'libraries'},
        ),
        migrations.AddField(
            model_name='language',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
