# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20151223_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='tutorials', to='languages.Library'),
        ),
    ]
