# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_tutorial_libraries'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='package_url',
            field=models.URLField(blank=True, default=b'', max_length=2048),
        ),
        migrations.AlterField(
            model_name='library',
            name='homepage_url',
            field=models.URLField(blank=True, default=b'', max_length=1024),
        ),
    ]
