# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_auto_20151223_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='url',
            new_name='tutorial_url',
        ),
    ]
