# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_auto_20151224_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='source_code_url',
            field=models.URLField(blank=True, default=b'', max_length=2048),
        ),
    ]
